dirkules/dirkules/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('samba/', include('samba.urls', namespace="samba")),
]

dirkules/samba/urls.py
from django.urls import path

from . import views

app_name = 'samba'

urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('add', views.add, name='add'),
]

dirkules/cleaning/views.py
from flask import request, redirect, flash, render_template, url_for, Blueprint

from dirkules import db
from dirkules.cleaning import manager as cleaning_manager

from dirkules.cleaning.models import Cleaning
from dirkules.cleaning.validation import CleaningForm

bp_cleaning = Blueprint('cleaning', __name__, template_folder='templates')


@bp_cleaning.route('/', methods=['GET'])
def index():
    remove = request.args.get('remove')
    changestate = request.args.get('changestate')
    service = request.args.get('service')
    if not (remove is not None and changestate is not None):
        if remove is not None:
            try:
                remove = int(remove)
                Cleaning.query.filter(Cleaning.id == remove).delete()
                db.session.commit()
                return redirect(request.path, code=302)
            except ValueError:
                flash("Value Error: remove")
        elif changestate is not None:
            try:
                changestate = int(changestate)
                job = Cleaning.query.get_or_404(changestate)
                job.change_active()
                db.session.commit()
                return redirect(request.path, code=302)
            except ValueError:
                flash("Value Error: changestate")
    else:
        flash("Value Error: remove and changestate set")
    if service is not None:
        try:
            service = str(service)
            if service == "start":
                if not cleaning_manager.running():
                    cleaning_manager.enable()
                    return redirect(request.path, code=302)
                else:
                    flash("Error: Cleaning Service already running.")
            elif service == "pause":
                if cleaning_manager.running():
                    cleaning_manager.disable()
                    return redirect(request.path, code=302)
                else:
                    flash("Error: Cleaning Service already paused.")
            else:
                raise ValueError
        except ValueError:
            flash("Value Error: service")
    elements = Cleaning.query.order_by(db.asc(db.collate(Cleaning.name, 'NOCASE'))).all()
    return render_template('cleaning/index.html', elements=elements, task_running=cleaning_manager.running())


@bp_cleaning.route('/add', methods=['GET', 'POST'])
def add():
    form = CleaningForm(request.form)
    if request.method == 'POST' and form.validate():
        cleaning_manager.create_cleaning_obj(form.jobname.data, form.path.data, form.active.data)
        return redirect(url_for('.index'))
    return render_template('cleaning/add.html', form=form)

dirkules/drives/views.py
import dirkules.drives.manager as manager
from dirkules.models import Drive
from flask import Blueprint, request, url_for, redirect, render_template, abort

bp_drives = Blueprint('drives', __name__, template_folder='templates')


@bp_drives.route('/', methods=['GET'])
def index():
    delete = request.args.get('delete')
    if delete is not None:
        try:
            manager.delete_drive_by_id(int(delete))
        except ValueError:
            abort(500, description="Expected int, but got {}: {}.".format(type(delete), delete))
        return redirect(url_for('.index'))
    return render_template('drives/index.html', drives=Drive.query.all())


@bp_drives.route('/<drive_id>', methods=['GET'])
def detail(drive_id):
    try:
        drive = manager.get_drive_by_id(int(drive_id))
    except ValueError:
        abort(500, description="Expected int, but got {}: {}.".format(type(drive_id), drive_id))
    return render_template('drives/detail.html', parts=drive.partitions)

dirkules/pools/views.py
import datetime
import subprocess
from time import sleep

from dirkules import scheduler

from . import manager
from dirkules.models import Pool
from flask import Blueprint, render_template, abort, redirect, url_for, request

from .validation import PoolAddForm

bp_pools = Blueprint('pools', __name__, template_folder='templates')


@bp_pools.route('/', methods=['GET'])
def index():
    return render_template('pools/index.html', pools=Pool.query.all())


@bp_pools.route('/<pool>', methods=['GET'])
def detail(pool):
    try:
        db_pool = Pool.query.get_or_404(int(pool))
    except ValueError:
        abort(500, description="Expected int, but got {}: {}.".format(type(pool), pool))
    return render_template('pools/detail.html', pool=db_pool)


@bp_pools.route('/add', methods=['GET', 'POST'])
def add():
    form = PoolAddForm(request.form)
    form.drives.choices = manager.get_empty_drives()
    if request.method == 'POST' and form.validate():
        try:
            manager.create_btrfs_pool(form)
        except subprocess.CalledProcessError as e:
            abort(500, description="While creating a pool, the following exception occured: {}".format(e))
        except subprocess.TimeoutExpired as e:
            abort(500, description="Pool creation took too long: {}".format(e))
        scheduler.get_job("refresh_disks").modify(next_run_time=datetime.datetime.now())
        sleep(1)
        return redirect(url_for('.index'))
    return render_template('pools/pool_add.html', form=form)

dirkules/samba/views.py
from dirkules import db

from dirkules.config import staticDir
from flask import render_template, url_for, request, redirect, flash, Blueprint
from dirkules.samba import manager as smb_man
from dirkules.samba.models import SambaShare, SambaGlobal
from dirkules.samba.validation import SambaConfigForm, SambaAddForm, SambaRemovalForm


bp_samba = Blueprint('samba', __name__, template_folder='templates')


@bp_samba.route('/', methods=['GET'])
def index():
    e_share = request.args.get('enable')
    d_share = request.args.get('disable')
    shares = SambaShare.query.order_by(db.asc(db.collate(SambaShare.name, 'NOCASE'))).all()
    if not (e_share is not None and d_share is not None):
        if e_share is not None:
            try:
                e_share = int(e_share)
                share = SambaShare.query.get_or_404(e_share)
                smb_man.enable_share(share)
            except ValueError:
                flash("ValueError: enable", category="error")
            except LookupError:
                flash("LookupError: id not valid", category="error")
            return redirect(url_for('.index'))
        elif d_share is not None:
            try:
                d_share = int(d_share)
                share = SambaShare.query.get_or_404(d_share)
                smb_man.disable_share(share)
            except ValueError:
                flash("ValueError: disable", category="error")
            except LookupError:
                flash("LookupError: id not valid", category="error")
            return redirect(url_for('.index'))
    else:
        flash("Value Error: enable and disable set", category="error")
    return render_template('samba/index.html', shares=shares)


@bp_samba.route('/config', methods=['GET', 'POST'])
def config():
    form = SambaConfigForm(request.form)
    if SambaGlobal.query.first() is not None:
        form.workgroup.data = SambaGlobal.query.get(1).value
        form.server_string.data = SambaGlobal.query.get(2).value
    if request.method == 'POST' and form.validate():
        smb_man.set_samba_global(form.workgroup.data, form.server_string.data)
        return redirect(url_for('.index'))
    file = open(staticDir + "/conf/samba_global.conf", "r")
    conf = list()
    while True:
        line = file.readline()
        if line != '':
            conf.append(line.rstrip())
        else:
            break
    return render_template('samba/config.html', form=form, conf=conf)


@bp_samba.route('/add', methods=['GET', 'POST'])
def add():
    form = SambaAddForm(request.form)
    form.path.choices = smb_man.get_pools()
    if request.method == 'POST' and form.validate():
        smb_man.create_share(form.name.data, form.path.data, form.user.data, form.dir_mask.data, form.create_mask.data,
                             form.writeable.data, form.btrfs.data, form.recycling.data)
        return redirect(url_for('.index'))
    return render_template('samba/add.html', form=form)


@bp_samba.route('/generate')
def generate():
    smb_man.generate_smb()
    if SambaGlobal.query.first() is None:
        flash("Samba wurde nicht konfiguriert. Es wird der default fallback verwendet", category="warn")
    flash("Konfiguration erfolgreich generiert", category="positive")
    return redirect(url_for('.index'))


@bp_samba.route('/remove', methods=['GET', 'POST'])
def remove():
    share_id = request.args.get('share')
    show_modal = False
    if share_id is None:
        flash("Keine id angegeben. Möglicherweise ist der Verweis veraltet", category="error")
        return redirect(url_for('.index'))
    else:
        try:
            form = SambaRemovalForm(request.form)
            share_id = int(share_id)
            share = SambaShare.query.get_or_404(share_id)
            if request.method == 'POST':
                if form.validate():
                    smb_man.remove_share(share, remove_data=bool(form.remove_data.data))
                    return redirect(url_for('.index'))
                else:
                    show_modal = True
            return render_template('samba/remove.html', name=share.name, form=form, show_modal=show_modal)
        except ValueError:
            flash("ValueError: id is not an int", category="error")
        return redirect(url_for('.index'))

dirkules/templates/_formhelpers.html
{% macro render_field(field) %}
    {% if (field.type == 'StringField' or field.type == 'IntegerField') %}
        {% if field.errors %}
            <div class="field error">
        {% else %}
            <div class="field">
        {% endif %}
    {{ field.label }}
    {% if field.errors %}
        {% for error in field.errors %}
            <div class="ui pointing below red basic label">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    {{ field(**kwargs)|safe }}
    </div>
    {% elif field.type == 'SelectField' %}
        <div class="field">
        {% if field.errors %}
            <div class="ui mymindrop selection dropdown error">
        {% else %}
            <div class="ui mymindrop selection dropdown">
        {% endif %}
    <input type="hidden" name="{{ field.id }}">
    <i class="dropdown icon"></i>
    <div class="default text">{{ field.label.text }}</div>
    <div class="menu">
        {% for value, label in field.choices %}
            <div class="item" data-value="{{ value }}">{{ label }}</div>
        {% endfor %}
    </div>
    </div>
    </div>
    {% elif field.type == 'BooleanField' or field.type == 'ToggleBooleanField' %}
        {% if field.errors %}
            <div class="field error">
        {% else %}
            <div class="field">
        {% endif %}

        {% if field.type == 'BooleanField' %}
            <div class="ui checkbox">
        {% else %}
            <div class="ui toggle checkbox">
        {% endif %}
    {{ field(**kwargs)|safe }}
    {{ field.label }}
    </div>
    </div>
    {% elif field.type == 'RadioField' %}
        {% if field.label.text is defined and field.label.text|length %}
            <label>{{ field.label.text }}</label>
        {% endif %}
        {% for value, label in field.choices %}
            <div class="field">
                <div class="ui radio checkbox">
                    {% if value == 1 %}
                        <input type="radio" name="{{ field.id }}" value="{{ value }}" checked="">
                    {% else %}
                        <input type="radio" name="{{ field.id }}" value="{{ value }}">
                    {% endif %}
                    <label>{{ label }}</label>
                </div>
            </div>
        {% endfor %}
    {% elif field.type == 'SubmitField' %}
        <a onclick="history.back(-1)">
            <div class="ui button">
                Zurück
            </div>
        </a>
        <button class="ui primary button" type="submit">{{ field.label }}</button>
    {% elif field.type == 'SemanticMultiSelectField' %}
        <div class="inline field">
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="ui pointing below red basic label">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
        {% if field.errors %}
            <div class="ui fluid multiple search selection dropdown error">
        {% else %}
            <div class="ui fluid multiple search selection dropdown">
        {% endif %}
    <input type="hidden" name="{{ field.id }}">
    <i class="dropdown icon"></i>
    <div class="default text">{{ field.label.text }}</div>
    <div class="menu">
        {% for value, label in field.choices %}
            <div class="item" data-value="{{ value }}">{{ label }}</div>
        {% endfor %}
    </div>
    </div>
    </div>
    {% else %}
        This field is not defined in formhelpers.
    {% endif %}
{% endmacro %}

dirkules/templates/about.html
{% extends "base.html" %}
{% block title %}Über Dirkules{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="title">
        <h1>Über Dirkules</h1>
    </div>
    <div class="ui text container">
        <h3>Dirkules Version {{ version }}</h3>
        <p>
            Dirkules - Benannt nach einem großartigen Mitbewohner. Immer zur Stelle, um deinen Server zu überwachen.
        </p>
        <p>
            Das Projekt soll eine kleine, schnelle und einfache Weboberfläche erschaffen, welche es ermöglicht, die
            Wichtigesten Informationen sofort zu erfassen und ein paar kleine Einstellungen vorzunehmen.<br>
            Dirkules wurde hauptsächlich für die Verwaltung von BtrFS Volumes geschreiben, um alle modernen Features
            dieses Dateisystems zu nutzen und leicht zugänglich zu machen.
        </p>
        <p>
            Es ist dabei auf meine Anwendungsfälle zugeschnitten.
        </p>
        <div class="ui text center aligned container">
            <h2>Entwickelt von Technikamateur</h2>
            <a class="ui secondary basic button" href="https://github.com/technikamateur/dirkules">
                <i class="code icon"></i>
                Dirkules auf Github
            </a>
        </div>
    </div>
{% endblock %}

dirkules/templates/base.html
{% extends "semanticui/base.html" %}
{% block styles %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/myStyle.css') }}"/>
{% endblock %}

{% block messages %}
    <nav class="ui mymenu inverted massive menu">
        <a class="item" href="{{ url_for('index') }}"><i class="smile icon"></i> Startseite</a>
        <a class="item" href="/nzbget"><i class="download icon"></i> NZBGet</a>
        <a class="item" href="{{ url_for('drives.index') }}"><i class="hdd icon"></i> Festplatten</a>
        <a class="item" href="{{ url_for('pools.index') }}"><i class="server icon"></i> Pools</a>
        <a class="item" href="{{ url_for('cleaning.index') }}"><i class="trash icon"></i> Cleaning</a>
        <a class="item" href="{{ url_for('samba.index') }}"><i class="share alternate icon"></i> Samba</a>
        <div class="right menu">
            <a class="ui item" href="{{ url_for('about') }}">über Dirkules</a>
        </div>
    </nav>

    {% with errors = get_flashed_messages(category_filter=["error"]) %}
        {% if errors %}
            <div class="tablebox">
                <div class="ui negative message">
                    <i class="close icon"></i>
                    <div class="header">
                        Ein oder Mehrere Fehler sind aufgetreten
                    </div>
                    <ul class="list">
                        {% for msg in errors %}
                            <li>{{ msg }}</li>
                        {% endfor -%}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endwith %}

    {% with warns = get_flashed_messages(category_filter=["warn"]) %}
        {% if warns %}
            <div class="tablebox">
                <div class="ui warning message">
                    <i class="close icon"></i>
                    <div class="header">
                        Ein oder Mehrere Warnungen sind aufgetreten
                    </div>
                    <ul class="list">
                        {% for msg in warns %}
                            <li>{{ msg }}</li>
                        {% endfor -%}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endwith %}

    {% with info = get_flashed_messages(category_filter=["info"]) %}
        {% if info %}
            <div class="tablebox">
                <div class="ui message">
                    <i class="close icon"></i>
                    <div class="header">
                        Folgende Informationen sind vorhanden
                    </div>
                    <ul class="list">
                        {% for msg in info %}
                            <li>{{ msg }}</li>
                        {% endfor -%}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endwith %}

    {% with pos = get_flashed_messages(category_filter=["positive"]) %}
        {% if pos %}
            <div class="tablebox">
                <div class="ui positive message">
                    <i class="close icon"></i>
                    <div class="header">
                        Folgendes wurde erfolgreich abgeschlossen
                    </div>
                    <ul class="list">
                        {% for msg in pos %}
                            <li>{{ msg }}</li>
                        {% endfor -%}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <script>
        $('.message .close')
            .on('click', function () {
                $(this)
                    .closest('.message')
                    .transition('fade')
                ;
            })
        ;
    </script>
{% endblock %}

dirkules/templates/drives.html
{% extends "base.html" %}
{% block title %}Festplatten{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <h1 class="ui dividing header">Festplatten</h1>
        <table class="ui very basic celled table">
            <thead>
            <tr>
                <th>Laufwerk</th>
                <th>Name</th>
                <th>Speicherplatz</th>
                <th>SMART</th>
                <th>Aktionen</th>
            </tr>
            </thead>

            <tbody>
            {% for drive in drives %}
                <tr>
                    {% if drive.missing %}
                        <td class="collapsing error"><i class="attention icon"></i> Laufwerk nicht
                            gefunden: {{ drive.name }}</td>
                    {% else %}
                        <td class="collapsing"><i class="hdd icon"></i> {{ drive.name }}</td>
                    {% endif %}
                    <td>{{ drive.model }}</td>
                    <td class="right aligned">{{ drive.size|filesizeformat(true) }}</td>
                    {% if drive.smart %}
                        <td class="collapsing center aligned"><i class="large green checkmark icon"></i></td>
                    {% else %}
                        <td class="collapsing error center aligned"><i class="attention icon"></i></td>
                    {% endif %}
                    <td>
                        <a href="{{ url_for('partitions', part=drive.id) }}"
                           class="ui primary basic button">
                            <i class="server icon"></i>
                            Partitionen
                        </a>
                        <a href="{{ url_for('drives', delete=drive.id) }}">
                            <div class="ui orange basic button" data-tooltip="Use this, if drive doesn't exist anymore." data-position="top left">
                                <i class="trash icon"></i> Aus Datenbank löschen
                            </div>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dirkules/templates/error_page_skeleton.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/error_page.css') }}"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<svg width="380px" height="500px" viewBox="0 0 837 1045" version="1.1" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <path d="M353,9 L626.664028,170 L626.664028,487 L353,642 L79.3359724,487 L79.3359724,170 L353,9 Z"
              id="Polygon-1" stroke="#007FB2" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M78.5,529 L147,569.186414 L147,648.311216 L78.5,687 L10,648.311216 L10,569.186414 L78.5,529 Z"
              id="Polygon-2" stroke="#EF4A5B" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M773,186 L827,217.538705 L827,279.636651 L773,310 L719,279.636651 L719,217.538705 L773,186 Z"
              id="Polygon-3" stroke="#795D9C" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M639,529 L773,607.846761 L773,763.091627 L639,839 L505,763.091627 L505,607.846761 L639,529 Z"
              id="Polygon-4" stroke="#F2773F" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M281,801 L383,861.025276 L383,979.21169 L281,1037 L179,979.21169 L179,861.025276 L281,801 Z"
              id="Polygon-5" stroke="#36B455" stroke-width="6" sketch:type="MSShapeGroup"></path>
    </g>
</svg>
<div class="message-box">
    {% block messagebox %}
    {% endblock %}
    <div class="buttons-con">
        <div class="action-link-wrap">
            <a onclick="history.back(-1)" class="link-button link-back-button">Ein Schritt zurück</a>
            <a href="/" class="link-button">Zur Startseite</a>
        </div>
    </div>
</div>
</body>
</html>

dirkules/templates/index.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <h1 class="ui dividing header center aligned">Willkommen bei Dirkules</h1>
        <div class="infobox">
            <div class="ui info message">
                <i class="close icon"></i>
                <div class="header">
                    Bitte beachten
                </div>
                <p>
                    Ich übernehme keine Garantie oder Haftung für Fehlfunktionen.<br>Die Benutzung erfolgt auf
                    eigenes Risiko!<br>Dennoch wünsche ich viel Spaß, Dirkules wird sein Bestes geben ;)
                </p>
            </div>
        </div>
    </div>
    <div class="ui container">
        <table class="ui celled table">
            <thead>
            <tr>
                <th>Status</th>
                <th>Service</th>
            </tr>
            </thead>

            <tbody>
            {% for key in service %}
                <tr>
                    {% if service[key] %}
                        <td class="collapsing positive center aligned"><i class="icon checkmark"></i></td>
                    {% else %}
                        <td class="collapsing negative center aligned"><i class="attention icon"></i></td>
                    {% endif %}
                    <td>{{ key }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dirkules/templates/monitoring.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block nav %}
<div class="nav-wrapper green darken-4">
  <ul id="nav-mobile" class="right hide-on-med-and-down">
    <li><a href="{{ url_for('about') }}" class="right">über Dirkules</a></li>
  </ul>
  <ul id="nav-mobile" class="left hide-on-med-and-down">
    <li><a href="{{ url_for('index') }}">Startseite</a></li>
    <li><a href="/nzbget">NZBGet</a></li>
    <li class="active"><a href="{{ url_for('monitoring') }}">Monitoring</a></li>
  </ul>
</div>
{% endblock %}
{% block body %}
  <div class="title">
    <t1>Monitoring</t1>
  </div>
  <div class="tablebox">
    <table class="striped">
         <thead>
           <tr>
               <th>Laufwerk</th>
               <th>Einhängepunkt</th>
               <th>Dateisystem</th>
           </tr>
         </thead>

         <tbody>
           {% for drive in drives %}
           <tr>
             <td>{{drive.device}}</td>
             <td>{{drive.mountpoint}}</td>
             <td>{{drive.fstype}}</td>
           </tr>
           {% endfor %}
         </tbody>
       </table>
   </div>
{% endblock %}

dirkules/templates/partitions.html
{% extends "base.html" %}
{% block title %}Partitionen{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <h1 class="ui dividing header">Partitionen</h1>
        {% if parts is defined and parts|length %}
            <table class="ui celled striped table">
                <thead>
                <tr>
                    <th>Partition</th>
                    <th>Label</th>
                    <th>UUID</th>
                    <th>Größe</th>
                    <th>Dateisystem</th>
                    <th>Mountpoint</th>
                </tr>
                </thead>

                <tbody>
                {% for part in parts %}
                    <tr>
                        <td>{{ part.name }}</td>
                        <td>{{ part.label }}</td>
                        <td>{{ part.uuid }}</td>
                        <td>{{ part.size|filesizeformat(true) }}</td>
                        <td>{{ part.fs }}</td>
                        <td>{{ part.mountpoint }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="ui message">
                <div class="header">
                    Keine Partitionen gefunden
                </div>
                <p>Dieses Laufwerk besitzt keine Partitionen.</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

dirkules/templates/pools.html
{% extends "base.html" %}
{% block title %}Pools{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <div class="infobox">
            <div class="ui info message">
                <i class="close icon"></i>
                <div class="header">
                    Hinweis
                </div>
                <p>
                    Ein Pool muss eingehängt sein, um alle Informationen, wie Größe, RAID-Level und Mountoptions,
                    korrekt einzulesen.
                </p>
            </div>
        </div>
        <a href="{{ url_for('add_pool') }}">
            <div class="ui primary labeled icon button">
                <i class="plus icon"></i> Neuen Pool erstellen
            </div>
        </a>
        <table class="ui celled table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Größe</th>
                <th>Frei</th>
                <th>Typ</th>
                <th>Dateisystem</th>
                <th>Mountpoint</th>
                <th>Disks</th>
                <th>Aktionen</th>
            </tr>
            </thead>

            <tbody>
            {% for pool in pools %}
                <tr>
                    <td><i class="download icon"></i> {{ pool.label }}</td>
                    <td class="right aligned">{{ pool.size|filesizeformat(true) }}</td>
                    {% if pool.free == 2 %}
                        <td class="right aligned">unbekannt</td>
                    {% else %}
                        <td class="right aligned">{{ pool.free|filesizeformat(true) }}</td>
                    {% endif %}
                    <td>{{ pool.data_raid }}</td>
                    <td>{{ pool.fs }}</td>
                    {% if pool.mountpoint|length %}
                        <td>{{ pool.mountpoint }}</td>
                    {% else %}
                        <td>nicht eingehängt</td>
                    {% endif %}
                    <td>{{ pool.drives }}</td>
                    <td>
                        <a href="{{ url_for('pool', pool=(pool.id)) }}"
                           class="ui primary basic button">
                            <i class="eye icon"></i>
                            Details
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dirkules/templates/samba_add.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="ui container">
        <t2>Neue Samba Share einrichten</t2>
        {% from "_formhelpers.html" import render_field %}
        <form method=post class="ui form error">
            <h4 class="ui dividing header">Allgemeine Informationen</h4>
            {{ render_field(form.name) }}
            <div class="fields">
                {{ render_field(form.writeable) }}
                {{ render_field(form.recycling) }}
                {{ render_field(form.btrfs) }}
            </div>
            <h4 class="ui dividing header">Erweiterte Informationen</h4>
            {{ render_field(form.path) }}
            {{ render_field(form.user) }}
            <div class="fields">
                {{ render_field(form.create_mask) }}
                {{ render_field(form.dir_mask) }}
            </div>
            <button class="ui button" type="submit"><i class="plus icon"></i> Freigabe hinzufügen</button>
        </form>
    </div>
    <script>
        $(document).ready(function () {
            $('.ui.dropdown').dropdown();
        });
    </script>
{% endblock %}