dirkules/dirkules/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('samba/', include('samba.urls', namespace="samba")),
]

dirkules/samba/urls.py
from django.urls import path

from . import views

app_name = 'samba'

urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('add', views.add, name='add'),
]

dirkules/samba/models.py
from django.db import models


class SambaGlobal(models.Model):
    element = models.CharField(max_length=255)
    value = models.CharField(max_length=255)


class SambaShare(models.Model):
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=255)
    recycle = models.BooleanField()
    btrfs = models.BooleanField()
    enabled = models.BooleanField()


class SambaOption(models.Model):
    option = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    share = models.ForeignKey(SambaShare, on_delete=models.CASCADE)

dirkules/samba/forms.py
from django import forms

class SambaConfigForm(forms.Form):
    workgroup = forms.CharField(label="workgroup", max_length=11)
    server_string = forms.CharField(label="server string", max_length=15)

dirkules/samba/views.py
from dirkules import db

from dirkules.config import staticDir
from flask import render_template, url_for, request, redirect, flash, Blueprint
from dirkules.samba import manager as smb_man
from dirkules.samba.models import SambaShare, SambaGlobal
from dirkules.samba.validation import SambaConfigForm, SambaAddForm, SambaRemovalForm


bp_samba = Blueprint('samba', __name__, template_folder='templates')


@bp_samba.route('/', methods=['GET'])
def index():
    e_share = request.args.get('enable')
    d_share = request.args.get('disable')
    shares = SambaShare.query.order_by(db.asc(db.collate(SambaShare.name, 'NOCASE'))).all()
    if not (e_share is not None and d_share is not None):
        if e_share is not None:
            try:
                e_share = int(e_share)
                share = SambaShare.query.get_or_404(e_share)
                smb_man.enable_share(share)
            except ValueError:
                flash("ValueError: enable", category="error")
            except LookupError:
                flash("LookupError: id not valid", category="error")
            return redirect(url_for('.index'))
        elif d_share is not None:
            try:
                d_share = int(d_share)
                share = SambaShare.query.get_or_404(d_share)
                smb_man.disable_share(share)
            except ValueError:
                flash("ValueError: disable", category="error")
            except LookupError:
                flash("LookupError: id not valid", category="error")
            return redirect(url_for('.index'))
    else:
        flash("Value Error: enable and disable set", category="error")
    return render_template('samba/index.html', shares=shares)


@bp_samba.route('/config', methods=['GET', 'POST'])
def config():
    form = SambaConfigForm(request.form)
    if SambaGlobal.query.first() is not None:
        form.workgroup.data = SambaGlobal.query.get(1).value
        form.server_string.data = SambaGlobal.query.get(2).value
    if request.method == 'POST' and form.validate():
        smb_man.set_samba_global(form.workgroup.data, form.server_string.data)
        return redirect(url_for('.index'))
    file = open(staticDir + "/conf/samba_global.conf", "r")
    conf = list()
    while True:
        line = file.readline()
        if line != '':
            conf.append(line.rstrip())
        else:
            break
    return render_template('samba/config.html', form=form, conf=conf)


@bp_samba.route('/add', methods=['GET', 'POST'])
def add():
    form = SambaAddForm(request.form)
    form.path.choices = smb_man.get_pools()
    if request.method == 'POST' and form.validate():
        smb_man.create_share(form.name.data, form.path.data, form.user.data, form.dir_mask.data, form.create_mask.data,
                             form.writeable.data, form.btrfs.data, form.recycling.data)
        return redirect(url_for('.index'))
    return render_template('samba/add.html', form=form)


@bp_samba.route('/generate')
def generate():
    smb_man.generate_smb()
    if SambaGlobal.query.first() is None:
        flash("Samba wurde nicht konfiguriert. Es wird der default fallback verwendet", category="warn")
    flash("Konfiguration erfolgreich generiert", category="positive")
    return redirect(url_for('.index'))


@bp_samba.route('/remove', methods=['GET', 'POST'])
def remove():
    share_id = request.args.get('share')
    show_modal = False
    if share_id is None:
        flash("Keine id angegeben. Möglicherweise ist der Verweis veraltet", category="error")
        return redirect(url_for('.index'))
    else:
        try:
            form = SambaRemovalForm(request.form)
            share_id = int(share_id)
            share = SambaShare.query.get_or_404(share_id)
            if request.method == 'POST':
                if form.validate():
                    smb_man.remove_share(share, remove_data=bool(form.remove_data.data))
                    return redirect(url_for('.index'))
                else:
                    show_modal = True
            return render_template('samba/remove.html', name=share.name, form=form, show_modal=show_modal)
        except ValueError:
            flash("ValueError: id is not an int", category="error")
        return redirect(url_for('.index'))

dirkules/samba/templates/samba/add.html
{% extends "base.html" %}
{% block title %}Freigabe hinzufügen{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="ui container">
        {% from "_formhelpers.html" import render_field %}
        {% if form.errors %}
            <form method=post class="ui form error">
        {% else %}
            <form method=post class="ui form">
        {% endif %}
            {{ form.hidden_tag() }}
            <h4 class="ui dividing header">Allgemeine Informationen</h4>
            {{ render_field(form.name) }}
            <div class="fields">
                {{ render_field(form.writeable) }}
                {{ render_field(form.recycling) }}
                {{ render_field(form.btrfs) }}
            </div>
            <h4 class="ui dividing header">Erweiterte Informationen</h4>
            {{ render_field(form.path) }}
            <div class="fields">
                {{ render_field(form.user) }}
                {{ render_field(form.create_mask) }}
                {{ render_field(form.dir_mask) }}
            </div>
            {{ render_field(form.submit) }}
        </form>
    </div>
    <script>
        $(document).ready(function () {
            $('.ui.dropdown').dropdown();
        });
    </script>
{% endblock %}

dirkules/samba/templates/samba/config.html
{% extends "base.html" %}
{% load semanticui %}
{% block title %}Dashboard{% endblock %}
{% block body %}
    <div class="ui container">
        <t2>Feste Bestandteile der<i> Samba global conf</i></t2>
        <div class="ui segment">
            {% for line in conf %}
                {{ line }}<br>
            {% endfor %}
        </div>
        <t2>Veränderbare Bestandteile der<i> Samba global conf</i></t2>
        <form method=post class="ui form">
            {% csrf_token %}
            {% render_form form %}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

dirkules/samba/templates/samba/index.html
{% extends "base.html" %}
{% block title %}Samba{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <a href="{% url 'samba:config' %}">
            <div class="ui primary labeled icon button">
                <i class="edit icon"></i> Konfigurieren
            </div>
        </a>
        <a href="{% url 'samba:add' %}">
            <div class="ui primary labeled icon button">
                <i class="plus icon"></i> Freigabe hinzufügen
            </div>
        </a>
        <a href="">
            <div class="ui primary labeled icon button">
                <i class="magic icon"></i> Generieren
            </div>
        </a>
        <table class="ui celled padded table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Pfad</th>
                <th class="collapsing">Papierkorb</th>
                <th class="collapsing">BtrFS Modul</th>
                <th>Aktionen</th>
            </tr>
            </thead>

            <tbody>
            {% for share in shares %}
                <tr>
                    <td>{{ share.name }}</td>
                    <td>{{ share.path }}</td>
                    {% if share.recycle %}
                        <td class="collapsing"><i class="check icon"></i> Aktiviert</td>
                    {% else %}
                        <td class="collapsing"><i class="close icon"></i> Deaktiviert</td>
                    {% endif %}
                    {% if share.btrfs %}
                        <td class="collapsing"><i class="check icon"></i> Aktiviert</td>
                    {% else %}
                        <td class="collapsing"><i class="close icon"></i> Deaktiviert</td>
                    {% endif %}
                    {% comment %} <td>{% if share.enabled %}
                        <a href="{{ url_for('.index', disable=share.id) }}">
                            <div class="ui orange icon basic button">
                                <i class="unlink icon"></i>
                            </div>
                        </a>
                    {% else %}
                        <a href="{{ url_for('.index', enable=share.id) }}">
                            <div class="ui green icon basic button">
                                <i class="linkify icon"></i>
                            </div>
                        </a>
                    {% endif %}
                        <a href="{{ url_for('.remove', share=share.id) }}">
                            <div class="ui red icon basic button">
                                <i class="trash icon"></i>
                            </div>
                        </a>
                    </td> {% endcomment %}
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dirkules/samba/templates/samba/remove.html
{% extends "base.html" %}
{% block title %}Freigabe entfernen{% endblock %}
{% block body %}
    <div class="topspacer"></div>
    <div class="ui container">
        <h2 class="ui center aligned icon header">
            <i class="circular trash icon"></i>
            <div class="content">
                Freigabe entfernen
                <div class="sub header">Sie möchten die Samba Freigabe mit dem Namen "{{ name }}" entfernen. Bitte
                    konkretisieren und bestätigen.
                </div>
            </div>
        </h2>
        {% from "_formhelpers.html" import render_field %}
        {% if form.errors %}
            <form method=post class="ui form error">
        {% else %}
            <form method=post class="ui form">
        {% endif %}
        {{ form.hidden_tag() }}
        {{ render_field(form.remove_data) }}
            {% if show_modal %}
                <div class="ui segment">
                {{ render_field(form.okay) }}
                </div>
                <div class="ui error message">
                    <i class="close icon"></i>
                    <div class="header">
                        Verletzung der Sicherheitsprotokolle
                    </div>
                    Die Sicherheitsprotokolle verhindern die automatische Ausführung.<br>
                    Für das Ausführen der gewünschten Aktion, ist eine Überbrückung der Sicherheitsprotokolle nötig.
                    Bitte bestätigen.
                </div>
            {% endif %}
        {{ render_field(form.submit) }}
        </form>
    </div>
{% endblock %}